random_seed: 42
target: churn

splits:
  train_frac: 0.7
  val_frac: 0.15
  test_frac: 0.15

drop_columns:
  - Count

numeric_features:
  - Tenure Months
  - Monthly Charges
  - Total Charges
  - Latitude
  - Longitude

categorical_features:
  - Senior Citizen
  - Country
  - State
  - City
  - Zip Code
  - Lat Long
  - Gender
  - Partner
  - Dependents
  - Phone Service
  - Multiple Lines
  - Internet Service
  - Online Security
  - Online Backup
  - Device Protection
  - Tech Support
  - Streaming TV
  - Streaming Movies
  - Contract
  - Paperless Billing
  - Payment Method